config/routes.rb
Rails.application.routes.draw do
    resources :snippets do
        resources :comments
    end

    get 'home/index'

    root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :snippet
end

app/models/snippet.rb
class Snippet < ApplicationRecord
	belongs_to :stash
	has_many :comments, dependent: :destroy
	validates :title, presence: true
end

app/models/stash.rb
class Stash < ApplicationRecord
	has_many :snippets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@snippet = Snippet.find(params[:snippet_id])
		@comment  = @snippet.comments.create(comment_params)
		redirect_to snippet_path(@snippet)
	end

	def destroy
		@snippet = Snippet.find(params[:snippet_id])
		@comment = @snippet.comments.find(params[:id])
		@comment.destroy
		redirect_to snippet_path(@snippet)
	end

	private
	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
	protect_from_forgery
	def index
		@snippets = Snippet.all
		@new_snippet_link = new_snippet_path
		render react_component: 'snippets', props: { snippets: @snippets,
                                                     new_snippet_link: @new_snippet_link }
	end

	def show
		@snippet = Snippet.find(params[:id])
		render react_component: 'show_snippet', props: { snippet: @snippet,
														 comments: @snippet.comments }
	end

	def new
		@snippet = Snippet.new
		# render 'new'
		render react_component: 'new_snippet', props: { snippet_index_link: snippets_path}
	end

	def edit
		@snippet = Snippet.find(params[:id])
		render react_component: 'edit_snippet', props: { snippet: @snippet,
														 snippet_index_link: snippets_path }
	end

	def create
		@snippet = Snippet.new(snippet_params)

		if @snippet.save
			redirect_to @snippet
		else
			render 'new'
		end
	end

	def update
		@snippet = Snippet.find(params[:id])

		if @snippet.update(snippet_params)
			redirect_to @snippet
		else
			render 'edit'
		end
	end

	def destroy
		@snippet = Snippet.find(params[:id])
		@snippet.destroy
		redirect_to snippets_path
	end

	private
		def snippet_params
			params.require(:snippet).permit(:title, :text)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
	<%= link_to 'Delete', [comment.snippet, comment],
				method: :delete,
				data: { confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@snippet, @snippet.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>
	<%= f.submit %>
<% end %>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Collecton of Snippets', controller: 'snippets' %>

app/views/layouts/_react_hot_assets.html.erb
<% if Rails.env.development? %>
  <script src='http://localhost:8080/assets/react_bundle.js'></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeStash</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'layouts/react_hot_assets' %>
    <%= yield %>
  </body>
</html>

app/views/snippets/_form.html.erb
<%= form_for @snippet do |f| %>

  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@snippet.errors.count, "error") %> prohibited
        this snippet from being saved:
      </h2>
      <ul>
        <% @snippet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/snippets/edit.html.erb
<h1>Editing snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<h1>List all snippets</h1>
<%= link_to 'New Snippet', new_snippet_path %>
<table>
<tr>
	<th>Title</th>
	<th>Text</th>
	<th colspan="3"></th>
</tr>
<%= @snippets.each do |snippet|  %>
	<tr>
		<td><%= snippet.title %></td>
		<td><%= snippet.text %></td>
		<td><%= link_to 'Show', snippet_path(snippet) %></td>
		<td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
		<td><%= link_to 'Delete', snippet_path(snippet),
						method: :delete,
						data: {confirm: 'Are you sure?'} %>
		</td>
	</tr>
<% end %>
</table>

app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @snippet.title %>
</p>
<p>
	<strong>Text:</strong>
	<%= @snippet.text %>
</p>

<h2>Comments</h2>
<%= render @snippet.comments %>

<h2>Add a comment: </h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>